from data_structures.trees.binary_tree_node import BinaryTreeNode
from linked_binary_tree_ext import LinkedBinaryTreeExt
class LinkedBinaryClientExt(LinkedBinaryTreeExt):
    nodo_a = BinaryTreeNode('A')
    nodo_b = BinaryTreeNode('B')
    nodo_c = BinaryTreeNode('C')
    nodo_d = BinaryTreeNode('D')
    nodo_f = BinaryTreeNode('F')
    nodo_g = BinaryTreeNode('G')
    nodo_h = BinaryTreeNode('H')
    nodo_i = BinaryTreeNode('I')
    nodo_k = BinaryTreeNode('K')
    nodo_m = BinaryTreeNode('M')
    nodo_n = BinaryTreeNode('N')
    arbol = LinkedBinaryTreeExt()
    arbol.add_root(nodo_a)
    arbol.add_left_child(nodo_a, nodo_b)
    arbol.add_right_child(nodo_a, nodo_f)
    arbol.add_left_child(nodo_b, nodo_c)
    arbol.add_right_child(nodo_b, nodo_d)
    arbol.add_left_child(nodo_f, nodo_g)
    arbol.add_right_child(nodo_f, nodo_k)
    arbol.add_left_child(nodo_g, nodo_h)
    arbol.add_right_child(nodo_g, nodo_i)
    arbol.add_left_child(nodo_k, nodo_m)
    arbol.add_right_child(nodo_k, nodo_n)
    print(arbol)
    arbol1 = arbol._vertical_str(nodo_a)
    print(arbol1)
    ancestro_comun = arbol.ancestro_mas_inmediato(nodo_d,nodo_m )
    print(ancestro_comun)
    nodos_hoja = arbol.hojas()
    print(nodos_hoja) 
    print(arbol.nivel(nodo_k))
    print(arbol.diametro()) 